name: Symfony

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Dependencies
      run: ssh ${{ env.USERNAME }}@${{ env.IP_HOST }} 'cd ${{ env.PATH }}; git pull'
    - name: Install Dependencies
      run: ssh ${{ env.USERNAME }}@${{ env.IP_HOST }} 'sudo docker exec i-am-avatar-php-fpm php yii migrate --interactive=0'
